services:
  - type: web
    name: elkasaby-standards-platform
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server_v2.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
